Add Pre reqs heading
alphagov/gds-pre-commit pull request #39
Opened 2020-03-17 17:24 UTC by 0atman

Fixes https://github.com/alphagov/gds-pre-commit/issues/34

2020-03-17 17:30 UTC, danjoneslf reviewed
Maybe we need some introductory text to explain that you can install the hooks without the registration. 

The TOTP 2FA should also be in here.

2020-03-17 17:46 UTC, danjoneslf commented on README.md
> +Currently, our registration script's github oauth flow only works with OTP keys (such as ubikeys), not TOTP keys. If you use such a key, please skip registration.
This text is not correct. We do support TOTP like Google Authenticator / Authy. We don't support YubiKey's Fido U2F (https://www.yubico.com/authentication-standards/fido-u2f/)

2020-03-17 18:26 UTC, akinnane approved these changes
LGTM

2020-03-18 12:35 UTC, seaemsi requested changes

2020-03-18 12:35 UTC, cmcnallygds commented on README.md
> +**Hook**
We should only use bold for UI text. I recommend using a H3 here or just normal text.

2020-03-18 12:35 UTC, cmcnallygds commented on README.md
> +The pre-commit framework is installed by pip, the python package manager. To install it on your machine either brew install it or get it from your distributions package manager (it might be called `p
We should capitalise Python

2020-03-18 12:35 UTC, cmcnallygds commented on README.md
> +Currently, our registration script's github oauth flow only works with OTP systems (such as Google authenticator or authy or yubikeys that type in a code). If you use a U2F system, please skip regist
GitHub OAuth flow

2020-03-18 12:35 UTC, cmcnallygds commented on README.md
> +Currently, our registration script's github oauth flow only works with OTP systems (such as Google authenticator or authy or yubikeys that type in a code). If you use a U2F system, please skip regist
Google Authenticator, Authy, YubiKeys

2020-03-18 12:35 UTC, cmcnallygds commented on README.md
>  If you are happy with the default location, just run the following two commands to install:
We should avoid words like 'just' and 'simply'

2020-03-18 12:35 UTC, cmcnallygds commented on pre-commit-plugins.md
> +**Please note that these hooks are found on the pre-commit website but have not all been tested**
Try to avoid using bold for non-UI text

2020-03-18 14:38 UTC, merged