fix case where the user has no git config
alphagov/gds-pre-commit pull request #58
Opened 2020-05-04 07:44 UTC by 0atman

Accidentally found this out after my 20.04 reinstall last week!

2020-05-04 11:36 UTC, akinnane requested changes

2020-05-04 11:36 UTC, akinnane commented on register.py
> +    if not username:
```suggestion
    if not username or not email:
```
Do we need to check for an invalid email too?

2020-05-04 11:49 UTC, 0atman commented on register.py
> +    if not username:
yes, yes we do

2020-05-05 07:11 UTC, 0atman commented
@akinnane look good now?

2020-05-05 08:02 UTC, akinnane approved these changes
Great, thanks.

2020-05-05 08:08 UTC, merged